spring:
    application:
        name: CO2Logger
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        url: jdbc:h2:mem:co2-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        driver-class-name: org.h2.Driver
        username: sa
        password:
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
#                use_sql_comments: true
#                format_sql: true
        database: h2
#        show-sql: true

metrics:
    metrics_days: 30
    threshold_ppm: 2000
    alert_threshold: 3